# Generated by Django 4.2.4 on 2023-08-12 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crypto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='update_date')),
                ('new_amount', models.DecimalField(decimal_places=5, default=0, max_digits=20, verbose_name='new_amount')),
                ('before_amount', models.DecimalField(decimal_places=5, default=0, max_digits=20, verbose_name='before_amount')),
                ('note', models.CharField(blank=True, max_length=100, null=True, verbose_name='note')),
                ('crypto_currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crypto.cryptocurrency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
