# Generated by Django 4.2.4 on 2023-08-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='update_date')),
                ('abbreviation', models.CharField(max_length=3, unique=True, verbose_name='crypto_abbreviation_name')),
                ('name', models.CharField(max_length=50, verbose_name='crypto_name')),
                ('purchase_price', models.DecimalField(decimal_places=5, default=0, max_digits=20, verbose_name='crypto_purchase_price')),
                ('sale_price', models.DecimalField(decimal_places=5, default=0, max_digits=20, verbose_name='crypto_sales_price')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Crypto logo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
